// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://melqkkgtqswdyqintjwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbHFra2d0cXN3ZHlxaW50andqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDU0MDksImV4cCI6MjA2NDQyMTQwOX0.bQY2Zz6v-jkn7Tnc275ZAfK5HjB6m70ScBGonqpOdFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);