// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gufhkckyeislippjubob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1ZmhrY2t5ZWlzbGlwcGp1Ym9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODY3ODMsImV4cCI6MjA2NjQ2Mjc4M30.nfgUqj7-H_NhUI_x4fIlJpI9BAh1ln8bXDGnGVSvTmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);